In [1]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualizaci贸n
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# y la distribuci贸n de las variables
# ------------------------------------------------------------------------------
#import scipy.stats as stats
import scipy.stats as stats
from scipy.stats import shapiro, kstest

# Configuraci贸n
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames 


# Gesti贸n de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

## Dataset: `menstrual_cycle_data.csv`

[Source](https://www.kaggle.com/datasets/nikitabisht/menstrual-cycle-data/data)

In [2]:
df_cycle_general = pd.read_csv('files/raw/menstrual_cycle_data.csv')

df_cycle_general.head()

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,TotalNumberofHighDays,TotalHighPostPeak,TotalNumberofPeakDays,TotalDaysofFertility,TotalFertilityFormula,LengthofMenses,MeanMensesLength,MensesScoreDayOne,MensesScoreDayTwo,MensesScoreDayThree,MensesScoreDayFour,MensesScoreDayFive,MensesScoreDaySix,MensesScoreDaySeven,MensesScoreDayEight,MensesScoreDayNine,MensesScoreDayTen,MensesScoreDay11,MensesScoreDay12,MensesScoreDay13,MensesScoreDay14,MensesScoreDay15,TotalMensesScore,MeanBleedingIntensity,NumberofDaysofIntercourse,IntercourseInFertileWindow,UnusualBleeding,PhasesBleeding,IntercourseDuringUnusBleed,Age,AgeM,Maristatus,MaristatusM,Yearsmarried,Wedding,Religion,ReligionM,Ethnicity,EthnicityM,Schoolyears,SchoolyearsM,OccupationM,IncomeM,Height,Weight,Reprocate,Numberpreg,Livingkids,Miscarriages,Abortions,Medvits,Medvitexplain,Gynosurgeries,LivingkidsM,Boys,Girls,MedvitsM,MedvitexplainM,Urosurgeries,Breastfeeding,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,5,0,2,9,15,5,4.49,3,3,2,1,1,,,,,,,,,,,10,9.04,5,1,0,,,36,39,0,0,10,,0,0,0,0,8,8,3,5,63,120,0,3,3,0,0,0,,,,,,0,,,0,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,2,0,2,6,13,5,,3,3,2,1,1,,,,,,,,,,,10,,6,1,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,1,0,2,5,13,5,,3,3,2,1,1,,,,,,,,,,,10,,5,1,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,2,0,2,6,13,5,,3,3,3,2,1,,,,,,,,,,,12,,3,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,4,0,2,8,14,5,,3,3,2,2,1,,,,,,,,,,,11,,5,1,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [4]:
df_cycle_general.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1665 entries, 0 to 1664
Data columns (total 80 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ClientID                    1665 non-null   object
 1   CycleNumber                 1665 non-null   int64
 2   Group                       1665 non-null   int64
 3   CycleWithPeakorNot          1665 non-null   int64
 4   ReproductiveCategory        1665 non-null   int64
 5   LengthofCycle               1665 non-null   int64
 6   MeanCycleLength             1665 non-null   object
 7   EstimatedDayofOvulation     1665 non-null   object
 8   LengthofLutealPhase         1665 non-null   object
 9   FirstDayofHigh              1665 non-null   object
 10  TotalNumberofHighDays       1665 non-null   object
 11  TotalHighPostPeak           1665 non-null   object
 12  TotalNumberofPeakDays       1665 non-null   object
 13  TotalDaysofFertility        1665 non-null   object
 14  TotalFertilityFormula       1665 non-null   object
 15  LengthofMenses              1665 non-null   object
 16  MeanMensesLength            1665 non-null   object
 17  MensesScoreDayOne           1665 non-null   object
 18  MensesScoreDayTwo           1665 non-null   object
 19  MensesScoreDayThree         1665 non-null   object
 20  MensesScoreDayFour          1665 non-null   object
 21  MensesScoreDayFive          1665 non-null   object
 22  MensesScoreDaySix           1665 non-null   object
 23  MensesScoreDaySeven         1665 non-null   object
 24  MensesScoreDayEight         1665 non-null   object
 25  MensesScoreDayNine          1665 non-null   object
 26  MensesScoreDayTen           1665 non-null   object
 27  MensesScoreDay11            1665 non-null   object
 28  MensesScoreDay12            1665 non-null   object
 29  MensesScoreDay13            1665 non-null   object
 30  MensesScoreDay14            1665 non-null   object
 31  MensesScoreDay15            1665 non-null   object
 32  TotalMensesScore            1665 non-null   object
 33  MeanBleedingIntensity       1665 non-null   object
 34  NumberofDaysofIntercourse   1665 non-null   object
 35  IntercourseInFertileWindow  1665 non-null   object
 36  UnusualBleeding             1665 non-null   object
 37  PhasesBleeding              1665 non-null   object
 38  IntercourseDuringUnusBleed  1665 non-null   object
 39  Age                         1665 non-null   object
 40  AgeM                        1665 non-null   object
 41  Maristatus                  1665 non-null   object
 42  MaristatusM                 1665 non-null   object
 43  Yearsmarried                1665 non-null   object
 44  Wedding                     1665 non-null   object
 45  Religion                    1665 non-null   object
 46  ReligionM                   1665 non-null   object
 47  Ethnicity                   1665 non-null   object
 48  EthnicityM                  1665 non-null   object
 49  Schoolyears                 1665 non-null   object
 50  SchoolyearsM                1665 non-null   object
 51  OccupationM                 1665 non-null   object
 52  IncomeM                     1665 non-null   object
 53  Height                      1665 non-null   object
 54  Weight                      1665 non-null   object
 55  Reprocate                   1665 non-null   object
 56  Numberpreg                  1665 non-null   object
 57  Livingkids                  1665 non-null   object
 58  Miscarriages                1665 non-null   object
 59  Abortions                   1665 non-null   object
 60  Medvits                     1665 non-null   object
 61  Medvitexplain               1665 non-null   object
 62  Gynosurgeries               1665 non-null   object
 63  LivingkidsM                 1665 non-null   object
 64  Boys                        1665 non-null   object
 65  Girls                       1665 non-null   object
 66  MedvitsM                    1665 non-null   object
 67  MedvitexplainM              1665 non-null   object
 68  Urosurgeries                1665 non-null   object
 69  Breastfeeding               1665 non-null   object
 70  Method                      1665 non-null   object
 71  Prevmethod                  1665 non-null   object
 72  Methoddate                  1665 non-null   object
 73  Whychart                    1665 non-null   object
 74  Nextpreg                    1665 non-null   object
 75  NextpregM                   1665 non-null   object
 76  Spousesame                  1665 non-null   object
 77  SpousesameM                 1665 non-null   object
 78  Timeattemptpreg             1665 non-null   object
 79  BMI                         1665 non-null   object
dtypes: int64(5), object(75)
memory usage: 1.0+ MB

In [31]:
df_cycle_general.columns

Index(['ClientID', 'CycleNumber', 'Group', 'CycleWithPeakorNot',
       'ReproductiveCategory', 'LengthofCycle', 'MeanCycleLength',
       'EstimatedDayofOvulation', 'LengthofLutealPhase', 'FirstDayofHigh',
       'TotalNumberofHighDays', 'TotalHighPostPeak', 'TotalNumberofPeakDays',
       'TotalDaysofFertility', 'TotalFertilityFormula', 'LengthofMenses',
       'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo',
       'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive',
       'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight',
       'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11',
       'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14',
       'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity',
       'NumberofDaysofIntercourse', 'IntercourseInFertileWindow',
       'UnusualBleeding', 'PhasesBleeding', 'IntercourseDuringUnusBleed',
       'Age', 'AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding',
       'Religion', 'ReligionM', 'Ethnicity', 'EthnicityM', 'Schoolyears',
       'SchoolyearsM', 'OccupationM', 'IncomeM', 'Height', 'Weight',
       'Reprocate', 'Numberpreg', 'Livingkids', 'Miscarriages', 'Abortions',
       'Medvits', 'Medvitexplain', 'Gynosurgeries', 'LivingkidsM', 'Boys',
       'Girls', 'MedvitsM', 'MedvitexplainM', 'Urosurgeries', 'Breastfeeding',
       'Method', 'Prevmethod', 'Methoddate', 'Whychart', 'Nextpreg',
       'NextpregM', 'Spousesame', 'SpousesameM', 'Timeattemptpreg', 'BMI'],
      dtype='object')

In [11]:
df_cycle_general['ClientID'].unique()

array(['nfp8122', 'nfp8114', 'nfp8109', 'nfp8107', 'nfp8106', 'nfp8024',
       'nfp8020', 'nfp8026', 'nfp8030', 'nfp8031', 'nfp8032', 'nfp8034',
       'nfp8036', 'nfp8040', 'nfp8041', 'nfp8042', 'nfp8043', 'nfp8045',
       'nfp8046', 'nfp8047', 'nfp8049', 'nfp8050', 'nfp8051', 'nfp8057',
       'nfp8058', 'nfp8060', 'nfp8062', 'nfp8063', 'nfp8064', 'nfp8066',
       'nfp8068', 'nfp8069', 'nfp8072', 'nfp8073', 'nfp8074', 'nfp8076',
       'nfp8079', 'nfp8080', 'nfp8083', 'nfp8085', 'nfp8087', 'nfp8091',
       'nfp8094', 'nfp8099', 'nfp8100', 'nfp8101', 'nfp8102', 'nfp8110',
       'nfp8113', 'nfp8116', 'nfp8123', 'nfp8124', 'nfp8129', 'nfp8131',
       'nfp8133', 'nfp8137', 'nfp8140', 'nfp8143', 'nfp8144', 'nfp8149',
       'nfp8150', 'nfp8152', 'nfp8154', 'nfp8155', 'nfp8159', 'nfp8161',
       'nfp8164', 'nfp8165', 'nfp8168', 'nfp8172', 'nfp8173', 'nfp8174',
       'nfp8176', 'nfp8177', 'nfp8178', 'nfp8179', 'nfp8184', 'nfp8186',
       'nfp8187', 'nfp8188', 'nfp8189', 'nfp8190', 'nfp8192', 'nfp8193',
       'nfp8195', 'nfp8196', 'nfp8197', 'nfp8200', 'nfp8206', 'nfp8207',
       'nfp8209', 'nfp8210', 'nfp8211', 'nfp8212', 'nfp8218', 'nfp8221',
       'nfp8223', 'nfp8226', 'nfp8228', 'nfp8229', 'nfp8230', 'nfp8233',
       'nfp8234', 'nfp8235', 'nfp8236', 'nfp8237', 'nfp8238', 'nfp8240',
       'nfp8242', 'nfp8244', 'nfp8246', 'nfp8247', 'nfp8248', 'nfp8249',
       'nfp8252', 'nfp8253', 'nfp8254', 'nfp8257', 'nfp8260', 'nfp8263',
       'nfp8264', 'nfp8266', 'nfp8268', 'nfp8269', 'nfp8270', 'nfp8271',
       'nfp8272', 'nfp8276', 'nfp8278', 'nfp8279', 'nfp8281', 'nfp8282',
       'nfp8284', 'nfp8286', 'nfp8288', 'nfp8289', 'nfp8290', 'nfp8292',
       'nfp8293', 'nfp8294', 'nfp8296', 'nfp8298', 'nfp8299', 'nfp8302',
       'nfp8303', 'nfp8305', 'nfp8306', 'nfp8308', 'nfp8309', 'nfp8310',
       'nfp8311', 'nfp8312', 'nfp8313', 'nfp8317', 'nfp8322', 'nfp8323',
       'nfp8324', 'nfp8328', 'nfp8334'], dtype=object)

In [17]:
df_filtered = df_cycle_general.groupby('ClientID')['CycleNumber'].apply(list)

In [22]:
df_filtered[-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [32]:
df_cycle_general['Group'].unique()

array([0, 1], dtype=int64)

In [34]:
df_cycle_general['CycleWithPeakorNot'].unique()

array([1, 0], dtype=int64)

In [36]:
df_cycle_general['ReproductiveCategory'].unique()

array([0, 2, 1, 9], dtype=int64)

In [44]:
df_cycle_general['ClientID'][df_cycle_general['MeanCycleLength'] == ' '].count()

1524

In [46]:
df_cycle_general['FirstDayofHigh'].unique()

array(['12', '13', ' ', '10', '9', '8', '14', '11', '16', '6', '15', '17',
       '21', '7', '19', '18', '5', '22', '20', '24', '23', '26', '25'],
      dtype=object)

In [47]:
df_cycle_general['ClientID'][df_cycle_general['FirstDayofHigh'] == ' '].count()

258

In [49]:
df_cycle_general['ClientID'].nunique()

159

In [51]:
df_cycle_general['MensesScoreDayTwo'].unique()

array(['3', '2', '1', ' '], dtype=object)

The dataset is too long and it contains useless columns for our objectives. We decide to select the columns that might be of use.

In [54]:
df_cycle_general = df_cycle_general[['ClientID', 'CycleNumber', 'LengthofCycle', 'MeanCycleLength', 'EstimatedDayofOvulation', 'LengthofLutealPhase', 'LengthofMenses',
       'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo', 'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive',
       'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight', 'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11',
       'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14', 'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity', 
       'UnusualBleeding', 'PhasesBleeding', 'Age', 'Ethnicity', 'BMI']]

In [58]:
df_cycle_general['ClientID'][df_cycle_general['MeanMensesLength'] == ' '].count()

1524

In [62]:
menses_columns  = [col for col in df_cycle_general if "Menses" in col]

menses_columns

['LengthofMenses',
 'MeanMensesLength',
 'MensesScoreDayOne',
 'MensesScoreDayTwo',
 'MensesScoreDayThree',
 'MensesScoreDayFour',
 'MensesScoreDayFive',
 'MensesScoreDaySix',
 'MensesScoreDaySeven',
 'MensesScoreDayEight',
 'MensesScoreDayNine',
 'MensesScoreDayTen',
 'MensesScoreDay11',
 'MensesScoreDay12',
 'MensesScoreDay13',
 'MensesScoreDay14',
 'MensesScoreDay15',
 'TotalMensesScore']

In [67]:
for col in menses_columns:
    print(col, '-->', df_cycle_general['ClientID'][df_cycle_general[col] == ' '].count())
    print(df_cycle_general[col].unique())
    print('=' * 50)

LengthofMenses --> 4
['5' '4' '6' '7' '10' '3' '8' '2' '9' '11' ' ' '15']
==================================================
MeanMensesLength --> 1524
['4.49' ' ' '4.5' '6.67' '4.75' '4.33' '4.67' '5.31' '6' '5.63' '5.33'
 '5.5' '5.2' '4.63' '5.45' '6.42' '6.5' '3.92' '5' '5.14' '6.23' '5.54'
 '7' '3.9' '4.69' '4.25' '7.14' '4.38' '4' '3.67' '3.23' '4.46' '5.69'
 '4.54' '2.85' '6.75' '8.58' '5.62' '5.67' '4.77' '6.38' '4.45' '5.8'
 '5.21' '6.45' '3.83' '4.83' '5.25' '4.22' '6.07' '2.4' '6.21' '5.08'
 '5.12' '6.25' '5.92' '3.94' '4.17' '6.88' '5.75' '3.5' '6.86' '5.17'
 '5.89' '5.84' '5.6' '7.46' '8.25' '5.16' '6.53' '4.7' '4.92' '7.08'
 '5.73' '5.64' '4.47' '4.85']
==================================================
MensesScoreDayOne --> 4
['3' '1' '2' ' ']
==================================================
MensesScoreDayTwo --> 4
['3' '2' '1' ' ']
==================================================
MensesScoreDayThree --> 25
['2' '3' '1' ' ']
==================================================
MensesScoreDayFour --> 87
['1' '2' '3' ' ']
==================================================
MensesScoreDayFive --> 434
['1' ' ' '2' '3']
==================================================
MensesScoreDaySix --> 1062
[' ' '1' '2' '3']
==================================================
MensesScoreDaySeven --> 1441
[' ' '1' '2' '3']
==================================================
MensesScoreDayEight --> 1597
[' ' '1' '2']
==================================================
MensesScoreDayNine --> 1639
[' ' '1' '2']
==================================================
MensesScoreDayTen --> 1659
[' ' '1']
==================================================
MensesScoreDay11 --> 1663
[' ' '1' '2']
==================================================
MensesScoreDay12 --> 1664
[' ' '2']
==================================================
MensesScoreDay13 --> 1664
[' ' '2']
==================================================
MensesScoreDay14 --> 1664
[' ' '1']
==================================================
MensesScoreDay15 --> 1664
[' ' '1']
==================================================
TotalMensesScore --> 4
['10' '12' '11' '9' '8' '6' '7' '13' '14' '15' '17' '5' '18' '16' '3' '4'
 '23' '19' '22' '24' '2' ' ' '20']
==================================================